TOKEN_TYPE_FIELD = "token_type"
ACCESS_TOKEN_TYPE = "access_token"
REFRESH_TOKEN_TYPE = "refresh_token"
RESET_PASSWORD_TOKEN_TYPE = "reset_account_password_token"
ADMIN_PANEL_ACCESS_TOKEN_TYPE = "admin_panel_access_token_type"
