services:
  app:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5050:8000"

  db:
    image: postgres:17.4-bookworm
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5051:${DB_PORT}"

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${MAIL_USERNAME}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "5052:80"
