"""Add FCMDeviceToken table

Revision ID: 799827db976e
Revises: ba15d84c6e75
Create Date: 2024-10-12 15:33:31.828622

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "799827db976e"
down_revision: Union[str, None] = "ba15d84c6e75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "firebaseDeviceToken",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("holder_id", sa.UUID(), nullable=False),
        sa.Column("device_token", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(["holder_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("firebaseDeviceToken")
    # ### end Alembic commands ###
