"""Notification table

Revision ID: 2f2c9e4da70c
Revises: 799827db976e
Create Date: 2024-10-14 20:59:15.763693

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f2c9e4da70c"
down_revision: Union[str, None] = "799827db976e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sender", sa.UUID(), nullable=False),
        sa.Column("recipient", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=True),
        sa.Column("text", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(length=6),
            server_default="UNREAD",
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["recipient"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sender"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification")
    # ### end Alembic commands ###
