"""empty message

Revision ID: 4f691a15dab3
Revises: 
Create Date: 2025-03-16 12:51:19.742765

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f691a15dab3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fileType",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("obj_type", sa.String(length=20), nullable=False),
        sa.CheckConstraint("char_length(obj_type) >= 3", name="min_obj_type_len_3"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("obj_type"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=32), nullable=True),
        sa.Column("last_name", sa.String(length=32), nullable=True),
        sa.Column("birthday", sa.Date(), nullable=True),
        sa.Column("sex", sa.String(length=6), nullable=True),
        sa.Column("nickname", sa.String(length=39), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=60), nullable=False),
        sa.Column("is_admin", sa.Boolean(), server_default="false", nullable=False),
        sa.CheckConstraint(
            "birthday >= DATE '1900-01-01' AND birthday <= CURRENT_DATE",
            name="check_birthday_1900",
        ),
        sa.CheckConstraint("sex IN ('Male', 'Female')", name="check_gender"),
        sa.CheckConstraint("char_length(first_name) >= 2", name="min_first_name_len_2"),
        sa.CheckConstraint("char_length(nickname) >= 5", name="min_nick_len_5"),
        sa.CheckConstraint(
            "char_length(password) >= 6 OR char_length(password) = 0",
            name="min_pass_len_6",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("nickname"),
    )
    op.create_table(
        "file",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("s3_path", sa.String(length=2083), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("type_id", sa.UUID(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.CheckConstraint("char_length(name) >= 6", name="min_file_name_len_6"),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["type_id"], ["fileType.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("s3_path"),
    )
    op.create_table(
        "firebaseDeviceToken",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("holder_id", sa.UUID(), nullable=False),
        sa.Column("device_token", sa.String(length=256), nullable=False),
        sa.CheckConstraint("char_length(device_token) >= 140", name="min_device_token_len_140"),
        sa.ForeignKeyConstraint(["holder_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "friend",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("friend_id", sa.UUID(), nullable=False),
        sa.Column(
            "relationship_type",
            sa.String(length=11),
            server_default="NOT_APPROVE",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["friend_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "friend_id", name="pk_user_id_friend_id"),
    )
    op.create_index(
        "uq_user_id_friend_id_permuted",
        "friend",
        [
            sa.literal_column("least(user_id, friend_id)"),
            sa.literal_column("greatest(user_id, friend_id)"),
        ],
        unique=True,
    )
    op.create_table(
        "notification",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sender", sa.UUID(), nullable=False),
        sa.Column("recipient", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=6),
            server_default="UNREAD",
            nullable=True,
        ),
        sa.CheckConstraint(
            "created_at >= DATE '1900-01-01' AND created_at <= CURRENT_TIMESTAMP",
            name="check_created_at_1900",
        ),
        sa.ForeignKeyConstraint(["recipient"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sender"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification")
    op.drop_index("uq_user_id_friend_id_permuted", table_name="friend")
    op.drop_table("friend")
    op.drop_table("firebaseDeviceToken")
    op.drop_table("file")
    op.drop_table("user")
    op.drop_table("fileType")
    # ### end Alembic commands ###
