"""add fcmdevicetoken table

Revision ID: 27cb28b020dd
Revises: ba15d84c6e75
Create Date: 2024-10-16 18:27:02.835630

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27cb28b020dd"
down_revision: Union[str, None] = "ba15d84c6e75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "firebaseDeviceToken",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("holder_id", sa.UUID(), nullable=False),
        sa.Column("device_token", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(["holder_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notification",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sender", sa.UUID(), nullable=False),
        sa.Column("recipient", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=True),
        sa.Column("message", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=6),
            server_default="UNREAD",
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["recipient"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sender"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification")
    op.drop_table("firebaseDeviceToken")
    # ### end Alembic commands ###
