"""empty message

Revision ID: a908af2235e2
Revises: 1604516de9f0
Create Date: 2024-11-18 18:55:05.965145

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a908af2235e2"
down_revision: Union[str, None] = "1604516de9f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fileType",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("obj_type", sa.String(length=20), nullable=False),
        sa.CheckConstraint("char_length(obj_type) >= 3", name="min_obj_type_len_3"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "file",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("s3_path", sa.String(length=2083), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("type", sa.UUID(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.CheckConstraint("char_length(name) >= 6", name="min_file_name_len_6"),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["type"], ["fileType.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("file")
    op.drop_table("fileType")
    # ### end Alembic commands ###
