"""empty message

Revision ID: 0969b7cdf072
Revises: 4907e7f6a1f4
Create Date: 2025-04-20 19:08:17.310505

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0969b7cdf072"
down_revision: Union[str, None] = "4907e7f6a1f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reactionType",
        "type",
        existing_type=postgresql.ENUM("LIKE", "LOVE", "FIRE", "SAD", name="reaction_type_enum"),
        type_=sa.Enum(
            "LIKE",
            "LOVE",
            "FIRE",
            "SAD",
            name="reaction_type_enum",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reactionType",
        "type",
        existing_type=sa.Enum(
            "LIKE",
            "LOVE",
            "FIRE",
            "SAD",
            name="reaction_type_enum",
            native_enum=False,
        ),
        type_=postgresql.ENUM("LIKE", "LOVE", "FIRE", "SAD", name="reaction_type_enum"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
