"""empty message

Revision ID: ec05665ceedb
Revises: 45d94a62289f
Create Date: 2023-10-05 21:49:56.308538

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ec05665ceedb'
down_revision: Union[str, None] = '45d94a62289f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('quantity_like', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'quantity_like')
    # ### end Alembic commands ###
