"""empty message

Revision ID: 2c9e421bc826
Revises: 1df36541a28c
Create Date: 2023-11-03 12:19:32.165804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c9e421bc826'
down_revision: Union[str, None] = '1df36541a28c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('liked_posts_user_id_fkey', 'liked_posts', type_='foreignkey')
    op.create_foreign_key(None, 'liked_posts', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'liked_posts', type_='foreignkey')
    op.create_foreign_key('liked_posts_user_id_fkey', 'liked_posts', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
